spring:
  datasource:
    url: jdbc:postgresql://localhost:6436/ordershop01
    username: test1
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLdialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql

logging.level:
  org.hibernate.sql: debug # console에 남기지 않고 log파일에 남긴다.
