spring:
  datasource:
    url: jdbc:postgresql://localhost:6436/ordershop01
    username: test1
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 4

  jpa:
    hibernate.dialect: org.hibernate.dialect.PostgreSQLdialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 이 옵션을 사용하면 컬렉션이나, 프록시 객체를 한꺼번에 설정한 size 만큼 IN 쿼리로 조회한다.
    database: postgresql

logging.level:
  org.hibernate.sql: debug # console에 남기지 않고 log파일에 남긴다.
#  org.hibernate.type: trace
